# Generated by Django 5.0.7 on 2024-11-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Unit Name')),
                ('symbol', models.TextField(max_length=20, verbose_name='Unit Symbol')),
                ('scale', models.FloatField(default=1.0, verbose_name='Unit Scale')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unit_manager.unit')),
            ],
        ),
    ]
